{ ... }: {
  imports = [
    ./ags
    ./impermanence.nix
    ./git.nix
    ./launcher.nix
    ./statusBar.nix
    ./terminal.nix
    ./tmux.nix
    ./wm.nix
    ./coding
    ./cd.nix
    ./ls.nix
    ./find.nix
    ./notifications.nix
    ./file-explorer.nix
    ./communication.nix
    ./browser.nix
    ./image-editor.nix
    ./viewers.nix
    ./screenshot.nix
    ./notes.nix
    ./theme.nix
    ./calendar.nix
    ./casparcg.nix
    ./bottles.nix
    ./network.nix
    ./office.nix
    ./video-rec.nix
    ./shell.nix
    ./networkmanager.nix
    ./videoediting.nix
    ./ldtk.nix

    ./games/minecraft.nix
    ./games/terraria.nix
    ./games/rocket-league
    ./games/lutris.nix
  ];
}
