{...}: {
  imports = [
    ../../modules/home/ags

    ../../modules/home/impermanence.nix
    ../../modules/home/git.nix
    ../../modules/home/launcher.nix
    ../../modules/home/statusBar.nix
    ../../modules/home/terminal.nix
    ../../modules/home/tmux.nix
    ../../modules/home/wm.nix
    ../../modules/home/coding
    ../../modules/home/cd.nix
    ../../modules/home/ls.nix
    ../../modules/home/find.nix
    ../../modules/home/notifications.nix
    ../../modules/home/file-explorer.nix
    ../../modules/home/communication.nix
    ../../modules/home/browser.nix
    ../../modules/home/image-editor.nix
    ../../modules/home/viewers.nix
    ../../modules/home/screenshot.nix
    ../../modules/home/notes.nix
    ../../modules/home/theme.nix
    ../../modules/home/calendar.nix
    ../../modules/home/casparcg.nix
    ../../modules/home/bottles.nix
    ../../modules/home/office.nix
    ../../modules/home/video-rec.nix
    ../../modules/home/shell.nix
    ../../modules/home/network-tools.nix
    ../../modules/home/videoediting.nix
    ../../modules/home/ldtk.nix
    ../../modules/home/flatpak.nix
    ../../modules/home/godot.nix
    ../../modules/home/playit.nix
    ../../modules/home/zoom.nix
    ../../modules/home/blender.nix
    ../../modules/home/epic-games.nix
    ../../modules/home/genealogy.nix
    ../../modules/home/fonts.nix
    ../../modules/home/zotero.nix
    ../../modules/home/syncthing.nix
    ../../modules/home/sunshine.nix
    ../../modules/home/localsend.nix
    ../../modules/home/sound.nix
    ../../modules/home/audio-mix.nix
    ../../modules/home/onedrive.nix
    ../../modules/home/linuxshowplayer.nix
    ../../modules/home/gstreamer.nix
    ../../modules/home/password-manager.nix
    ../../modules/home/cad.nix
    ../../modules/home/email.nix
    ../../modules/home/shows.nix

    ../../modules/home/games/minecraft.nix
    ../../modules/home/games/terraria.nix
    ../../modules/home/games/rocket-league.nix
    ../../modules/home/games/steam.nix
    ../../modules/home/games/roblox.nix
    ../../modules/home/games/ets2.nix
    ../../modules/home/games/openttd.nix
    ../../modules/home/games/trackmania.nix
    ../../modules/home/games/lethal.nix
  ];
}
